baseURL = "https://www.historicist.com/"
disableLanguages = ["fr"]
disqusShortname = ""
googleAnalytics = "UA-219336890-1"
hasCJKLanguage = false
paginate = "6"
summaryLength = "20"
theme = "Historicist"
timeZone = "UTC"
title = "Historicist Biblical Interpretation"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.90.1"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
