[[footer]]
name = "About"
url = "about/"
weight = 1
[[footer]]
name = "Authors"
url = "author/"
weight = 2
[[footer]]
name = "Privacy"
url = "privacy/"
weight = 3
[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4
[[main]]
hasChildren = false
name = "Home"
url = "/"
weight = 1
[[main]]
name = "About"
url = "about/"
weight = 3
[[main]]
name = "Contact"
url = "contact/"
weight = 4
[[main]]
hasChildren = true
name = "Pages"
url = "#"
weight = 5
[[main]]
name = "Author"
parent = "Pages"
url = "author/"
weight = 1
[[main]]
name = "Tags"
parent = "Pages"
url = "tags/"
weight = 2
[[main]]
name = "Tag Single"
parent = "Pages"
url = "tags/photography/"
weight = 3
[[main]]
name = "Category"
parent = "Pages"
url = "categories/"
weight = 4
[[main]]
name = "Category Single"
parent = "Pages"
url = "categories/lifestyle/"
weight = 5
[[main]]
name = "Elements"
parent = "Pages"
url = "elements/"
weight = 6
